#!/bin/bash

# System Information
HOSTNAME=$(hostname)
DISTRO=$(cat /etc/os-release | grep PRETTY_NAME | cut -d '=' -f2 | tr -d '"')
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(cat /proc/cpuinfo | grep "model name" | head -n 1 | cut -d ':' -f2 | tr -s ' ')
CPU_SPEED=$(lscpu | grep "MHz" | awk '{print "Current: " $NF " MHz, Maximum: " $(NF-2) " MHz"}')
RAM=$(free -h | awk '/Mem/ {print $2}')
DISKS=$(lsblk -o NAME,SIZE,MODEL | grep -v "NAME")
VIDEO=$(lspci | grep -i "VGA\|3D\|2D" | awk -F ": " '{print $NF}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip route | grep default | awk '{print $3}')
DNS_IP=$(grep nameserver /etc/resolv.conf | awk '{print $2}')
INTERFACE=$(ip -o link show | awk -F': ' '{print $2}' | tr -d ' ' | grep -v "lo")
NETWORK_INFO=$(ip addr show $INTERFACE | grep -w "inet" | awk '{print $2}')

# System Status
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ',')
DISK_SPACE=$(df -h | awk '{print $1 " " $4}' | grep '^/')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3}')
MEMORY_ALLOCATION=$(free -h | grep Mem | awk '{print $1 ": " $2 ", " $3}')
LISTENING_PORTS=$(netstat -tuln | grep -v "Active" | awk '{print $4}' | cut -d ':' -f2 | sort -u | tr '\n' ',')
UFW_RULES=$(ufw show added | grep -v "^Status")

# Generating the report
echo ""
echo "System Report generated by $(whoami), $(date)"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $DISTRO"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "---------------------"
echo "cpu: $CPU"
echo "Speed: $CPU_SPEED"
echo "Ram: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_IP"
echo ""
echo "InterfaceName: $INTERFACE"
echo "IP Address: $NETWORK_INFO"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Memory Allocation: $MEMORY_ALLOCATION"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Rules: $UFW_RULES"
echo ""
